### ISSUE TITLE
Can you clarify how you get the data to fill in the accessory array?

### ISSUE THREAD

**Issue by poldim** [anthonywebb/homebridge-cbus#10]
I'm amazed that I've gotten this far.  I've got a ubuntu vm running cgate and homebridge.  I've added my wemo switches to homebridge and can see them in home kit.  Now trying to setup the homebridge-cbus platform has me stumped on how you come up with the values for the accessories array.  The following is the error message I'm getting on homebridge after it has a successful connection to cgate.

```
Message:GET //toledo/254/56/23 level

Message:GET //toledo/254/56/22 level

CBusStatusPacket {
  raw: '401 Bad object or device ID.',
  channel: 'controlStream',
  type: 'unknown',
  source: 'cbus' }
CBusStatusPacket {
  raw: '401 Bad object or device ID.',
  channel: 'controlStream',
  type: 'unknown',
  source: 'cbus' }
```

**Comment by anthonywebb** [comment]
Look for an xml file in the cgate director somewhere, it should have all the ID's (I think you are after ID's?)  I use cgate on windows and there is a GUI that lists all your devices and their ID's but I know that even the cgate command line version can dump a list of devices for you.  From there you will build your config in a txt editor.  Good luck!

**Comment by poldim** [comment]
Found the problem in cgate, I guess cgate needed to be told a bit more about the project before it would work.  This is what I did from the cgate CLI:

```
PROJECT DIR
123-project=EXAMPLE
123-project=TOLEDO

PROJECT LOAD TOLEDO
200 OK.

PROJECT USE TOLEDO
200 OK.

NET LIST
131 network=254 State=new InterfaceState=closed

NET OPEN 254
120-initializing
120-opening port
120-starting network threads
120-pci reset
120-checking connection
120-relinking to bridged networks
120-open complete
200 OK: //TOLEDO/254
```

After this I started homebridge and it's working.  The downside is that since I'm connecting to the Wiser CNI, it's killing the Wiser app's ability to control.  This means I can't implement this until it's fully rock solid, and I've got cgate and homebridge setup to auto start and boot in the vm...which I have no idea how to do in linux.

**Comment by simonhac** [comment]
fyi @poldim, i installed* c-gate on my synology NAS as i wanted to be able to access my network from:
* my 'production' homebridge installation
* my development environment (because i'm trying to write a plugin)
* and also the clipsal windows tools (which i'm running in a virtual box from my mac):
  * c-bus toolkit
  * PICED

i don't know how i'd achieve much at all without the c-bus toolkit.

\* by 'installed' i mean that i nohup'd cgate, which is pretty pathetic. i'm hoping to bundle up homebridge-cbus and cgate into a single docker container, building upon the excellent work of @marcoraddatz.

**Comment by poldim** [comment]
@simonhac, 

Are you accessing the cbus simultaneously or at different times? 

I'd love to see that Docket if you get it up and running.  I'd throw that on my unraid server rather than a full ubuntu VM...

**Comment by simonhac** [comment]
@poldim i'm using cgate simultaneously from all of the above. 

i'll let you know how i go with docker. i don't really know what i'm doing!

**Comment by marcoraddatz** [comment]
@simonhac Are you using the latest version of my Docker image? It's now supported to install all the dependencies you need via adding them to the `install.sh`.

**Comment by simonhac** [comment]
@marcoraddatz great to hear from you. yes, i am running your docker image and am immensely grateful for your work to build it.

do you have any interest in adding c-gate to the image? it would be awesome to have the whole 'box and dice' in a single container.

**Comment by marcoraddatz** [comment]
You're welcome! I'm not planning to do so—I want the image to be as slim as possible. But as proposed, you can easily add the missing dependencies via install.sh, which is executed as root. There's no need to add them to the Dockerfile.

**Comment by simonhac** [comment]
thanks @marcoraddatz i forgot for a moment that your docker container is a generic homebridge container, not a homebridge-cbus container, so it makes total sense that you wouldn't want to pull in stuff that 99% of folk don't need.

i'll try my hand at shell scripting to see if i can coax install.sh to check whether c-gate is installed, and if not, download and 'install' it. or perhaps its better to have a crack at writing a node wrapper to  install and manage it -- i'm very new to this. do you have a recommendation?

(fyi, cgate is a closed-source but publicly available server written in java. it is [available from the vendor's website as a zip file](http://203.41.170.20/downloads/CGate/cgate-2.10.6_3145.zip).)

**Comment by marcoraddatz** [comment]
I'd recommend to install cgate via another Docker container, so that you can connect both images. This should make be much easier to maintain on updates. The ports needed for communication could be set via Synology's internal reverse proxy.

**Comment by simonhac** [comment]
thanks @marcoraddatz -- sounds like a good solution. i'll give that a go at some point.

**Comment by simonhac** [comment]
@poldim wrote:
> Found the problem in cgate, I guess cgate needed to be told a bit more about the project before it would work. 

does this happen for everyone the first time they use C-Gate? if so, we could try to auto-configure C-Gate for the user...

**Comment by simonhac** [comment]
@poldim, from v0.5.7: accessory list can be build using platform_export -- see README.md -- which will greatly assist in filling in the accessory array.
