### ISSUE TITLE
Question - What is the default time in which Homebridge-cbus polls Cgate

### ISSUE THREAD

**Issue by SeanHama** [anthonywebb/homebridge-cbus#122]
Hi Guys, thanks for such an amazing plugin for my cbus. 
If I turn off the lights from the wall switch, how long does it take (should it take) for the state to be updated and shown in HomeKit/Homebridge?

**Comment by DarylMc** [comment]
It should be almost immediate

**Comment by DarylMc** [comment]
If it's not updating particularly on large networks it could be this problem.
Increase the Homebridge startup delay timer to say 10 minutes eg 600 seconds.
Then reboot
This allows CGATE to sync the network before Homebridge starts.
It's only at reboot so shouldn't cause you too much grief in normal use.
You could later experiment and reduce that time.

If that doesn't fix it might be worth checking the logs.

**Comment by SeanHama** [comment]
Thanks for the speedy time. I restared homebridge and now its back to instanteous. Might have been a small glitch somewhere with another plugin I was playing with which may have been slowing things down. My cbus network is not huge (around 18 devices).
It's all good now.

THANKS AGAIN FOR SUCH AN EXCELLENT AND RELIABLE PLUGIN. MADE MY CBUS AMAZING.
