### ISSUE TITLE
Auto-discover available groups and devices

### ISSUE THREAD

**Issue by simonhac** [anthonywebb/homebridge-cbus#13]
thought i'd start a discussion around how auto-discovery should be handled.

there are two ways i can think of to find out about devices that aren't configured: 
* monitor cbus network traffic and look for changes made to group addresses that we don't already know about
* suck out the contents of the c-gate database with DBGET or DBGETXML commands. from a quick look, i think we could build a list of all group addresses (with their tag names) and use the metadata of the associated unit devices to determine/guess the type of accessory.

on my network both of these methods would identify many group addresses that i don't want exposed to homebridge. so perhaps the auto-discovery should only build up a list of candidates, and then require manual intervention to expose to homebridge.

initially, the candidates could be dumped into a JSON file. eventually perhaps we could have a simple web UI that allows management of the accessory database -- add, remove, rename, show/hide accessories.

going further, it would certainly be useful to me to build out the accessory database with statistics such as:
* last change time, level (plus history)
* originator of last change
* affected units
* etc.

thoughts?

**Comment by gbrooker** [comment]
I agree, the auto discovery method would end up with quite a few units that were not useful for homebridge control. I was thinking a small stand alone utility which ran a TREE command on the C-Gate server and converted the output into configuration lines for homebridge config.json would be more useful. The user can then select which units to add, and give more friendly names for each of them.

**Comment by simonhac** [comment]
thanks @gbrooker for validating my thinking -- i've been playing with some code to suck down the `TREE` and build a full database so that i can give better debug information and also catch errors (eg. a relays configured as a dimmer, or a dimmer configured as a shutter).

 i'll have it dump the full database as a JSON file, which can then be hand edited and copied over to `config.json`.

**Comment by simonhac** [comment]
broken off the UI task into new issue #21.

**Comment by simonhac** [comment]
addressed with PR #20.
