### ISSUE TITLE
Issue with installing homebridge

### ISSUE THREAD

**Issue by peterconn** [anthonywebb/homebridge-cbus#132]
Having this issue and wondering if anyone has had a similar issue. The issue was when installing sudo npm install -g --unsafe-perm homebridge

As my PI crashed and SD failed im creating a new one. I did a backup of the img file but i cant find it so im starting from scratch.

sudo npm install -g --unsafe-perm homebridge
/usr/bin/homebridge -> /usr/lib/node_modules/homebridge/bin/homebridge
npm WARN notsup Unsupported engine for homebridge@1.5.0: wanted: {"node":">=10.17.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: homebridge@1.5.0
npm WARN notsup Unsupported engine for chalk@4.1.2: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: chalk@4.1.2
npm WARN notsup Unsupported engine for fs-extra@10.1.0: wanted: {"node":">=12"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: fs-extra@10.1.0
npm WARN notsup Unsupported engine for semver@7.3.7: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: semver@7.3.7
npm WARN notsup Unsupported engine for hap-nodejs@0.10.2: wanted: {"node":">=10.17.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: hap-nodejs@0.10.2
npm WARN notsup Unsupported engine for universalify@2.0.0: wanted: {"node":">= 10.0.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: universalify@2.0.0
npm WARN notsup Unsupported engine for fast-srp-hap@2.0.4: wanted: {"node":">=10.17.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: fast-srp-hap@2.0.4
npm WARN notsup Unsupported engine for lru-cache@6.0.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: lru-cache@6.0.0

TIA
Pete

**Comment by DarylMc** [comment]
Hi Peter
For a new setup I would use Greig's script.
It does have a current issue but it's not too hard to work around.

**Comment by DarylMc** [comment]
https://github.com/greiginsydney/Homebridge-cbus-installer/issues/22#issuecomment-1175558656

**Comment by peterconn** [comment]
Thank you all
