### ISSUE TITLE
HOOBS - Logs flooded

### ISSUE THREAD

**Issue by mattangelofdeth** [anthonywebb/homebridge-cbus#139]
Hi all,

I've recently had to migrate my old homebridge pi 3 to a 4, now running HOOBS.
The system was pretty bulletproof (until it bit the dust)

I appear to have most things now functional, however, the HOOBS logs are FLOODED with cbus errors and I was hoping someone could help decipher what they mean and what I could do to correct them.

I am not that familiar with the linux world, but I try to the point where I can endanger myself.

Any advice would be amazing as I just can't get by in life without this fantastic plugin working as it's intended

Errors are:
`21/11/2023, 14:08:20Cbus BridgeERROR2023-11-21T03:08:20.651Z cbus:client rx event { time: '20231121-140820', code: 735, processed: false, message: '//FAMILY/254 2d9c2880-68d9-103c-8123-c18e56809e82 cc004 sent cmd (fastpci): 1AF201z (254: \\461F001AF201z)', type: 'event', raw: '#e# 20231121-140820 735 //FAMILY/254 2d9c2880-68d9-103c-8123-c18e56809e82 cc004 sent cmd (fastpci): 1AF201z (254: \\461F001AF201z)' }
21/11/2023, 14:08:20Cbus BridgeERROR2023-11-21T03:08:20.760Z cbus:client rx event { time: '20231121-140820', code: 765, processed: false, message: '//FAMILY/254 2d9c2880-68d9-103c-8123-c18e56809e82 got packet confirm: z.', type: 'event', raw: '#e# 20231121-140820 765 //FAMILY/254 2d9c2880-68d9-103c-8123-c18e56809e82 got packet confirm: z.' }`
```

Thank you !!!

**Comment by DarylMc** [comment]
You could grab another SD and try following Greig or my setup instructions.
It's very fast to get everything going.

**Comment by DarylMc** [comment]
https://github.com/DarylMc/Homebridge-cbus-installer/blob/testing/SETUP.md

**Comment by DarylMc** [comment]
https://github.com/greiginsydney/Homebridge-cbus-installer

**Comment by mattangelofdeth** [comment]
Thanks, however, I have quite a bit invested on this install with other plugins and I’m keen to use hoobs this time around

**Comment by JasonY00** [comment]
You mention c-gate errors, but you don't mention if c-bus is actually working and talking to HOOBS...is it? Is is just the errors that you see that are annoying you, or are the errors indicative of you not being able to control your cbus system via siri/apple devices?

Are these messages only happening when you start everything up and then settle down after about 10min? When you initially connect to a c-bus network (and periodically) the network syncs and every device is queried and responds. This causes a lot of traffic (and messages) similar to what you observe which then settles down.

The message snippet you pasted show homebridge errors regarding C-Gate "command" and "PCI sync" events at CBUS event levels 9 and 8 respectively. (C-Gate Command "events e9" or "e8"). Event level 8 is set in homebridge-cbus in the "cgate-client" portion of the code. This event level was raised from level 7 so that homebridge could see temperature sensor broadcast events from the cbus network devices via c-gate. If this is set at 8, then I don't think you should be seeing the 735 errors in homebridge logs.

One further note about the homebridge-cbus code: It does not cater for the events 735 and 756. It really only cares about c-gate commands of 200, 300, 702 and 730. The rest it just sees as rubbish...

We can look further if the system is actually not working. If it is working, then don't worry. If you are worried about log sizes, get the homebridge-log-cleaner plugin to manage it.

Cheers

Jason

**Comment by mattangelofdeth** [comment]
Jason, Thanks so much for taking the time to write such a lengthy response.

The system is working as it should. The errors just appear to be in the masses in the logs, so I was concerned that I may have configured something incorrectly and that it would come back to haunt me down the path.
The errors are constant and don't appear to settle after any given time.

I will monitor it for the time being and see how it goes over the coming weeks.
Thanks for the insights into the commands and event id's, that's REALLY helpful!

**Comment by JasonY00** [comment]
No worries. I would expect the odd run of c-gate configuration messages (homebridge errors) everytime the network does a sync and these are of that format. Default sync interval in c-gate is every 3600 seconds, so on average every hour you should see these message commence and last for as long as it takes for the sync to settle down and complete. Larger and bridged networks take longer. My network has three segments across three bridges and about 200 devices, so it takes a little time to complete.... I would suggest running a terminal session to c-gate and watch the messages using the "events e8" command. That way you can see if there is any potential underlying problem with your c-bus network. Look at the c-gate manual that comes with the c-gate installation, it's in the root of the C-Gate2 directory when you install it. It will explain how to do this.

If you have a PC, you can run toolkit as well and watch the network commands/events in the live log.

Remember, that if your log gets too big, you can fill up your SD card over time. That is generally not good. As mentioned above, if it's compatible with HOOBS try the Homebridge-Log-Cleaner plugin. It manifests as a fan service under the home app with the rotation speed a function of how full the log is w.r.t. your preset size limit. If you "stop" the fan, it clears the log. When the fan hits 100% it clears the log and starts again at 0%. I recommend it if everything is working fine with your system and you don't look at it very often.

One final thing, if you run Homebridge in DEBUG mode, it may be more "verbose" with log entries. Once again, if everything is fine, you may be able to run it not in this mode. (Check if HOOBS has this setting. It should as it is just homebridge with a fancy wrapper)

Good luck and let us know how it all pans out...

Jason

**Comment by JasonY00** [comment]
One final note...I just ran a sync on my network and copied a bit of the c-gate log to show you what you see, it may look familiar to you:

20231121-214407 765 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 got packet confirm: l.
20231121-214407 735 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 cc017 sent cmd (fastpci): \46FC09422104m (252: \4642002104m)
20231121-214407 734 //JYOUNG/252 cae3e9b0-6a88-103c-8b26-8cbf000da155 response: 86FC0301408D0438FFFFAD531872808CB5000523 accepted by command: \4640002104j
20231121-214408 765 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 got packet confirm: m.
20231121-214408 735 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 cc016 sent cmd (fastpci): \4690002104n (254: \4690002104n)
20231121-214408 734 //JYOUNG/253 caca4730-6a88-103c-885e-8cbf000da155 response: 86FD0301C18D0439FFFF000018B62831BB01010C accepted by command: \46C1002104l
20231121-214408 734 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 response: 050A380079ED53 processed by network.
20231121-214408 702 //JYOUNG/254/56 cac08330-6a88-103c-8573-8cbf000da155 [lighting] automatic phantom group created at address 237
20231121-214408 730 //JYOUNG/254/56/237 cad4a770-6a88-103c-8634-8cbf000da155 new level=255 sourceunit=10 ramptime=0
20231121-214408 702 //JYOUNG/252/56 cae485f0-6a88-103c-8b2a-8cbf000da155 [lighting] automatic phantom group created at address 237
20231121-214408 730 //JYOUNG/252/56/237 cac676a0-6a88-103c-8bed-8cbf000da155 new level=255 sourceunit=-1 ramptime=0
20231121-214408 702 //JYOUNG/253/56 cacae370-6a88-103c-8862-8cbf000da155 [lighting] automatic phantom group created at address 237
20231121-214408 730 //JYOUNG/253/56/237 cacdf0b0-6a88-103c-8921-8cbf000da155 new level=255 sourceunit=-1 ramptime=0
20231121-214408 765 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 got packet confirm: n.
20231121-214408 735 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 cc018 sent cmd (fastpci): \46FD09C22104o (253: \46C2002104o)
20231121-214408 734 //JYOUNG/252 cae3e9b0-6a88-103c-8b26-8cbf000da155 response: 86FC0301428D04FFFFFF000018B3E932BB000504 accepted by command: \4642002104m
20231121-214408 734 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 response: 869003008D0438FFFF7D83186FB317B8010115 accepted by command: \4690002104n
20231121-214408 734 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 response: 05FC3801D201C330 processed by network.
20231121-214408 730 //JYOUNG/252/56/195 cabf23a0-6a88-103c-8bbd-8cbf000da155 new level=0 sourceunit=210 ramptime=0
20231121-214408 730 //JYOUNG/254/56/195 cacd5470-6a88-103c-8604-8cbf000da155 new level=0 sourceunit=-1 ramptime=0
20231121-214408 730 //JYOUNG/253/56/195 cac739f0-6a88-103c-88f5-8cbf000da155 new level=0 sourceunit=-1 ramptime=0
20231121-214408 765 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 got packet confirm: o.
20231121-214408 735 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 cc017 sent cmd (fastpci): \46FC09D02104p (252: \46D0002104p)
20231121-214408 734 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 response: 05FC3801D279C3B8 processed by network.
20231121-214408 730 //JYOUNG/252/56/195 cabf23a0-6a88-103c-8bbd-8cbf000da155 new level=255 sourceunit=210 ramptime=0
20231121-214408 730 //JYOUNG/254/56/195 cacd5470-6a88-103c-8604-8cbf000da155 new level=255 sourceunit=-1 ramptime=0
20231121-214408 730 //JYOUNG/253/56/195 cac739f0-6a88-103c-88f5-8cbf000da155 new level=255 sourceunit=-1 ramptime=0
20231121-214408 765 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 got packet confirm: p.
20231121-214408 735 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 cc016 sent cmd (fastpci): \4691002104q (254: \4691002104q)
20231121-214408 765 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 got packet confirm: q.
20231121-214408 735 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 cc018 sent cmd (fastpci): \46FD09032104r (253: \4603002104r)
20231121-214408 734 //JYOUNG/253 caca4730-6a88-103c-885e-8cbf000da155 response: 86FD0301C28D0439FFFF000018B67AC9BB010121 accepted by command: \46C2002104o
20231121-214408 734 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 response: 869103008D0438FFFF7D831871894ABB010106 accepted by command: \4691002104q
20231121-214408 734 //JYOUNG/252 cae3e9b0-6a88-103c-8b26-8cbf000da155 response: 86FC0301D08D0439FFFFFFFF18B311FCBA00054D accepted by command: \46D0002104p
20231121-214408 765 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 got packet confirm: r.
20231121-214408 735 //JYOUNG/254 cabfe6f0-6a88-103c-856f-8cbf000da155 cc017 sent cmd (fastpci): \46FC09D22104s (252: \46D2002104s)

**Comment by JasonY00** [comment]
Can you close this issue if you are happy?

cheers

Jason
