### ISSUE TITLE
% of the blind in Homekit, correspond with the blind itself

### ISSUE THREAD

**Issue by luke-b5114** [anthonywebb/homebridge-cbus#145]
Hi all, 

In Homekit, my blinds are displayed and working on an up/down basis but as soon as I want the blind at 70% down, the blind percentage does not correspond with the blind itself.

Hope this makes sense and someone can help. 

Thanks in advance.

**Comment by JasonY00** [comment]
Hi Luke,

Do you have shutter relays controlling your blinds?

If so, the percentage open/close may not correspond if the time it takes to open and close your blinds is not roughly equal to the "Duration" set under the "Fail safe" tab of the Shutter Relay configuration in Toolkit. Have a look to see what the value is. I usually set my duration to about 1-2 seconds more than the time taken to open the blind. The percentage open/closed roughly correlates to the duration. I use the opening duration as my metric as some heavy roller blinds open a little more slowly as they are pulling the blind mass against gravity when opening and close a little faster with the blind unrolling with gravity.

Use your watch to measure the opening time, add a couple of seconds and enter this in the "duration" and give it a go.

Let us know if this is the scenario and fix and if not, we can try something else.

By the way, what you are saying makes perfect sense!

Cheers

Jason

**Comment by luke-b5114** [comment]
Hi Jason,

Yes, shutter relays are controlling all blinds.

So pretty much, I need to set the "Duration" time 1-2 seconds more then it takes the blind to either open /or close ? 
(my blinds are just a standard fabric, not heavy at all)

Appreciate the fast response too

**Comment by JasonY00** [comment]
That’s pretty much it. Make sure you set a time for the blind to “fully” open with the small buffer. You can always change it again. That way you will get pretty close with the percentage open/close. It won’t be perfect, but with a bit of fine tuning it will be pretty close. If it works , then give a thumbs up and close the issue.
Cheers
Jason

**Comment by luke-b5114** [comment]
Awesome it worked ! 
Very happy now, 

Thank you
