### ISSUE TITLE
Solved: activeDuration not working

### ISSUE THREAD

**Issue by chromusphil** [anthonywebb/homebridge-cbus#148]
Homebridge Cbus v1.1.0

I am having trouble using the activeDuration tag to timeout devices eg extractor fans in bathroom and bell press for a garage door trigger.

Below is an example from my config that isn't working, I have consulted the MS lib and the documentation and can't find a reason for it not working. Has a bug crept in from an update to the Homebridge architecture or have I got the syntax wrong?

{
                    "type": "dimmer",
                    "id": 12,
                    "name": "Pwdr Light",
                    "activeDuration": "1m",
                    "enabled": true
                },

{
                    "type": "light",
                    "id": 42,
                    "name": "Garage Door",
                    "activeDuration": "2s",
                    "enabled": true
                },

**Comment by DarylMc** [comment]
From the readme I think it only works on switch type accessory.

**Comment by DarylMc** [comment]
![image](https://github.com/user-attachments/assets/c7e5f26b-1655-4723-a1ca-4fbeb6189855)

**Comment by chromusphil** [comment]
My apologies, i have small children and often only get to work on this stuff very late and missed that.
