### ISSUE TITLE
Fan support

### ISSUE THREAD

**Issue by anthonywebb** [anthonywebb/homebridge-cbus#2]
I'd like to add fan support to the plugin, problem is I have no fan on my clipsal.  Hoping someone out there with a fan and some knowledge of CGate can help me come up with the proper Cgate commands to control their fan.

You can see the fan services are supported here, we just need to wire them up.
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

**Comment by srpage** [comment]
Hi Anthony,
To control the fan relay in CGate I use the lighting app, The relay has 3 speeds and different ramp thresholds for the speeds.
It broadcasts the appropriate label with each speed.
Example assuming my fan is 221 and the thresholds are 0% Off, 33% for Speed Low and 66% for Speed Med & 100% for High.
Examples are -
Off = "ramp 254/56/221 0%"
Low = "ramp 254/56/221 30%"
Med = "ramp 254/56/221 60%"
High = "ramp 254/56/221 100%"  
For fan Off and High you can also use "off" or "on" 
Hope this helps.
Simon

**Comment by anthonywebb** [comment]
@simonhac I am wondering if the shutter stuff you just worked up would work for fans as well?  on the surface it seems like they are very similar?

**Comment by simonhac** [comment]
@anthonywebb i don't know -- it doesn't sound like the @srpage is using the shutter relay (L5501RBCP), but perhaps it is similar enough that i could have a crack at it.

hey @srpage, what relay are you using to control the fan?o

**Comment by srpage** [comment]
Gents,
I am using the L5501RFCP for the fans and L5501RBCP for my blinds.
I'll try and get some time to test the binds in the next day or so.
Reading through the blind thread it does look very similar to the blinds.
Would be very happy to test for you.
Simon

**Comment by simonhac** [comment]
gathering info:

### Ceiling Sweep Fan Control Relay L5501RFCP
* [Product Sheet](http://updates.clipsal.com/ClipsalOnline/Files/Brochures/W0001292.pdf)
* [Installation Instructions](http://updates.clipsal.com/ClipsalOnline/Files/Brochures/W0001291.pdf)

### HomeKit support
![image](https://cloud.githubusercontent.com/assets/20500649/22195604/f5d8537c-e19c-11e6-81a8-d4dc4efa0150.png)

so looks like it'll be pretty simple to implement `on/off` and `rotation speed` using the shutter control accessory as a base.

**Comment by anthonywebb** [comment]
@simonhac I was wondering where you got the screenshot you just posted?

**Comment by simonhac** [comment]
@anthonywebb the screenshot comes from Apple's [HomeKit Accessory Simulator](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/HomeKitDeveloperGuide/EnablingHomeKit/EnablingHomeKit.html#//apple_ref/doc/uid/TP40015050-CH2-SW3).

<img src="https://cloud.githubusercontent.com/assets/20500649/22195866/443f6310-e19e-11e6-87bc-8abf202f24d8.png" width="350">

**Comment by simonhac** [comment]
@srpage there's not much in the CIS docs i've posted above. unless you know of any other docs, i fear i'm going to have to sit through the youtubes:
* https://www.youtube.com/watch?v=mXZiUggST2k
* https://www.youtube.com/watch?v=KzPnWMaHjkU
* https://www.youtube.com/watch?v=gR3BJJvMf_M

**Comment by anthonywebb** [comment]
Not much about fans in the CGate docs, I suppose you probably control them just like you do lights with the ramp value being the speed? http://www.foresterit.com/CGateManual.pdf

**Comment by simonhac** [comment]
as expected, there's pretty good documentation in the Toolkit help doc:  **C-Bus ceiling sweep fan controller single master configuration tutorial**. (thanks CIS!)

there are three modes:
* stand-alone
* single master
* master and slaves

i haven't got my head around the master/slave stuff, but i bet that most folk use stand-alone.

@srpage are you using the stand-alone mode with the defaults?
![image](https://cloud.githubusercontent.com/assets/20500649/22198528/0c4bd3b4-e1ab-11e6-84dc-91079f60c0db.png)
![image](https://cloud.githubusercontent.com/assets/20500649/22198543/15f2be5a-e1ab-11e6-9c62-996520f2ccf8.png)

@anthonywebb you are right — from the docs:

> The C-Bus ceiling sweep fan controller has thresholds which determine the cutoff Lighting % level between low and medium speed and then again medium and high. The default thresholds are 34% and 67%.

**Comment by simonhac** [comment]
@srpage please consider responding to the question above.

also, in the interim, can you please consider adding a fan as a 'shutter' and seeing whether it work? (the icon / UI in the Home app will be all wrong, but i'd be interested to know if the control works.)

**Comment by srpage** [comment]
@simonhac 
Have added a fan as a shutter, worked straight away.
Open is high, Closed is Off and using the slider can control the speeds. Low, Med & High.
Pretty cool.
The other way of doing it might be to toggle a single button.
This is how I have them set up in my house using DLT's and a trigger group.

**Comment by simonhac** [comment]
thanks @srpage -- good to hear 'it just works'.

i'll still create a proper accessory for it so that you'll get whatever UI the Home app provides for fans, rather than have your fans look like window coverings!

**Comment by simonhac** [comment]
fixed in v0.5.8 (PR #28) -- not yet released to npmjs. 

ping @srpage -- since i don't have an actual fan control unit, i'd appreciate your feedback as to how well this works. (i tested it with a dimmer channel. i'm not sure how it will go if you use your DLT to toggle the speed…)

**Comment by srpage** [comment]
Fan looks to be working well on all but one.
I'll have a play in the next day or so and report back.
We use our fans on low mostly so I like how it remembers the previous setting if I toggle off and on as it just toggles Off and Low.

**Comment by simonhac** [comment]
thanks @srpage -- i'm interested to hear what happens when you set the level by your DLT, then use the Home app and then move back again.

also interested to hear more about "Fan looks to be working well on all but one."
