### ISSUE TITLE
Virtual Groups

### ISSUE THREAD

**Issue by xrsprint** [anthonywebb/homebridge-cbus#22]
thanks @xrsprint -- one question: does C-Gate know about the group? ie. can you see it in the database with the C-Bus Toolkit?

i think this could be easy to fix. can i ask you to please write this up as a separate issue and i'll look into it?

Hello Simon,

yes it is seen in toolkit, and operates identical to any other group, the only diffrence is the group is not assigned to a relay or dimmer

cheers

**Comment by simonhac** [comment]
@xrsprint i'm having trouble reproducing this with C-Gate.

i added a group with C-Bus toolkit -- group address 241, not assigned to any unit.

```
on //SHAC//254/56/241
200 OK: //SHAC/254/56/241
#e# 20170226-213704.684 730 //SHAC/254/56/241 a244dc60-de3c-1034-a827-fbb6c098d608 new level=255 sourceunit=12 ramptime=0 sessionId=cmd1753 commandId={none}

get //SHAC//254/56/241 level
300 //SHAC/254/56/241: level=255

off //SHAC//254/56/241
200 OK: //SHAC/254/56/241
#e# 20170226-213719.712 730 //SHAC/254/56/241 a244dc60-de3c-1034-a827-fbb6c098d608 new level=0 sourceunit=12 ramptime=0 sessionId=cmd1753 commandId={none}

get //SHAC//254/56/241 level
300 //SHAC/254/56/241: level=0
```

i tried again with a group that wasn't defined, and i get very similar output:

```
on //SHAC//254/56/242
200 OK: //SHAC/254/56/242
#e# 20170226-213834.469 730 //SHAC/254/56/242 - new level=255 sourceunit=12 ramptime=0 sessionId=cmd1753 commandId={none}

get //SHAC//254/56/242 level
300 //SHAC/254/56/242: level=255

off //SHAC//254/56/242
200 OK: //SHAC/254/56/242
#e# 20170226-213844.373 730 //SHAC/254/56/242 - new level=0 sourceunit=12 ramptime=0 sessionId=cmd1753 commandId={none}

get //SHAC//254/56/242 level
300 //SHAC/254/56/242: level=0
```

could you please show me a log of what C-Gate reports to you when you try to control groups that do not have physical units linked to them?

_(i have set the event level with `events e7s0c0`.)_

**Comment by xrsprint** [comment]
Hello Anthony

well i think i solved the issue, i upgraded to the new version to test the bell press, and now all virtual groups work, i was using the first release which i think was causing the issues, to me the whole thing looks diffrent from the old to the new version, and the bell press works like clock work, so i cant thank you enough for the effort you have put into this

just off topic, once i upgraded, and started everything from scratch, i have 2 small issues that i have noticed that might be a bug

- i have two groups, one called bedroom, which is a light and bedroom blind which is a shutter, when i turn on the bedroom light the shutter group status turns on, even though the relay hasn't triggered, it looks like the status of the shutter is mimicking the other lighting group

- i have three lighting groups, that turn on fine, but when you turn them off they are not turning off the cbus group, even though through toolkit i turn the group off, and it stays off, these groups were working fine on the old version

cheers

**Comment by simonhac** [comment]
@xrsprint, simon here. i'm glad that the bell press feature works for you.

if you can reproduce the issues you have mentioned above, please open a new issue and paste in logs from homekit-cbus (with DEBUG=cubs:*) including screen captures from the home app. that'll make the issue much clearer. 

please close this issue if you think the virtual group issue has been addressed.
