### ISSUE TITLE
Group status Changing when other group activated

### ISSUE THREAD

**Issue by xrsprint** [anthonywebb/homebridge-cbus#25]

**Comment by xrsprint** [comment]
Hi Guys,

attacehd are the logs and a screenshot, but what happens is when i turn the group bedroom on, the group bedroom blind shows in homekit that its also turned on, even though the cbus group did not change

i tried cahnging group names with no luck, thought that the same name could have caused issues

if you need any more info please let me know

Thanks

Damian

[group 8 copy.docx](https://github.com/anthonywebb/homebridge-cbus/files/806254/group.8.copy.docx)
![2017-02-28 18 37 37](https://cloud.githubusercontent.com/assets/24925789/23399696/405446ee-fdf5-11e6-93e2-3978444d7975.png)

**Comment by simonhac** [comment]
@xrsprint can you please take a look with `C-Bus Toolkit` to find out the `Unit Type` for _units_ 20 and 11?

i suspect unit 20 is your CNI/PC interface and unit 11 is a touch-screen (or some other kind of logic controller). it looks like the latter is firing off messages in response to the messages coming from `homebridge-cbus`.

**Comment by simonhac** [comment]
...also @xrsprint if you can update to the latest version of `homebridge-cbus` you'll get tags for your groups and devices in the log. eg.:

![image](https://cloud.githubusercontent.com/assets/20500649/23586643/66d60572-01ed-11e7-9d5a-a8e49ca6c28d.png)

that'd be useful to see.

**Comment by xrsprint** [comment]
Hello Simon

thanks and we can close this case, unit 11 was actually a 2 gang input which for some reason whenever the group with the shutter is on that unit it does what it does

thanks

**Comment by simonhac** [comment]
> unit 11 was actually a 2 gang input which for some reason whenever the group with the shutter is on that unit it does what it does

@xrsprint that's odd -- but glad that it's not a homebridge-cbus issue, because i would have been stumped!
