### ISSUE TITLE
Dimmer to On does not ramp brightness to 100

### ISSUE THREAD

**Issue by DeanAmbrosini** [anthonywebb/homebridge-cbus#3]
Only when the dimmer function is ramped up to 100 then down to 0 does the press on for the broup result in the brightness going to 100. If turned on from off the brightness in homebridge does not display/is not registered

**Comment by gbrooker** [comment]
I'm guessing that your CBus project address is not a word like HOME, but contains digits, like ABC3 or ROOM12. There was a bug in version 0.5.0 which stopped the plugin from being able to read cbus light status for projects with addresses which included digits. This is fixed in 0.5.1 and later.

**Comment by anthonywebb** [comment]
I am unable to duplicate, if this continues after updating to the latest version let me know and we can re-open.
