### ISSUE TITLE
Guess the type of the accessory from the database

### ISSUE THREAD

**Issue by simonhac** [anthonywebb/homebridge-cbus#33]
currently, when we suck down the group list via `dbgetxml` and stash into `config.json` we don't know the type of each group (unless it has been explicitly registered), and therefore just use the accessory type `unknown`.

there's no way to ask a group what type it is, but we can work out which unit/s is/are controlled by the group.

by looking at the `unitType` of the unit/s controlled by the group, we can make a pretty good guess of each accessory's `type`. if we are not 100% sure, we'll leave it as `unknown`.

**Comment by anthonywebb** [comment]
I would love it if there were some way to tell if it was connected to a dimmer unit or not?

**Comment by simonhac** [comment]
yep, it's pretty straightforward -- am halfway there but got distracted on a few other projects and a holiday. back at it after easter.

**Comment by simonhac** [comment]
completed in PR #47.
