### ISSUE TITLE
Update Problem

### ISSUE THREAD

**Issue by glenferguson** [anthonywebb/homebridge-cbus#35]
Hi all,

I have had Homebridge working great for a while and suddenly tonight the IOS device said it was connected but was not. I thought I would upgrade to version 0.5.8 from 0.5.3 however, I now get this error following the homekit code when I start homebridge. Cgate still running fine. Any help appreciated. 

Thanks 
Glen

  cbus:client sent command '[100] dbgetxml //HOMEKITM/254' +354ms
[3/14/2017, 9:57:06 PM] Homebridge is running on port 34574.
  cbus:client rx snippet 343 'Begin XML snippet' +28ms
  cbus:client rx snippet 347 '<?xml version="1.0" encoding="utf-8"?>' +1ms
  cbus:client rx snippet 347 '<Network><OID>8ef36500-eada-1034-ad90-a347dd1d27a0</OID><TagName>HKN</TagName><Address>254</Address…' +30ms
  cbus:client rx response { commandId: 100, code: 344, matched: false, processed: false, type: 'response', raw: '[100] 344 End XML snippet' } +18ms
  cbus:client matched response '[100] 344 End XML snippet' to request '[100] dbgetxml //HOMEKITM/254' (0 pending requests) +3ms
  cbus:client rx unparsable line: '[100] 344 End XML snippet', exception: TypeError: Cannot read property 'address' of undefined +994ms

**Comment by simonhac** [comment]
@glenferguson i'll look at the code tomorrow to see if i can find a way of instrumenting it better in this instance.

if you are impatient, you might want to downgrade.

**Comment by glenferguson** [comment]
Thanks Simon, appreciate the help

**Comment by simonhac** [comment]
@glenferguson hopefully you are comfortable helping with the debugging here.

1. please find the file `cgate-client.js` in your `homebridge-cbus` installation and change `${err}` in [line 646](https://github.com/anthonywebb/homebridge-cbus/blob/master/lib/cgate-client.js#L646) to `${err.stack}`. the line should then look like this:

```javascript
log(chalk.red(`rx unparsable line: '${line}', exception: ${err.stack}`));
```

then start `homebridge` again. you should get a stacktrace -- which will probably point to a line in `_parseXML` in `cgate-database.js`. it'll help me a lot to know which line.

i faked up an error and get the following:
![image](https://cloud.githubusercontent.com/assets/20500649/23932574/07a5683e-098d-11e7-9e82-32c84d3f21e6.png)

2. i'd also appreciate seeing how your C-Gate server responds to the `dbgetxml` command. 

please open a terminal window to your C-Gate (`telnet localhost 20023`) and enter `dbgetxml //HOMEKITM/254` and add the response to this ticket.

**Comment by glenferguson** [comment]
Hi Simon, here is what I had come back

 cbus:client sent command '[100] dbgetxml //HOMEKITM/254' +435ms
[3/15/2017, 9:15:38 PM] Homebridge is running on port 34574.
  cbus:client rx snippet 343 'Begin XML snippet' +371ms
  cbus:client rx snippet 347 '<?xml version="1.0" encoding="utf-8"?>' +32ms
  cbus:client rx snippet 347 '<Network><OID>92feb400-eb9e-1034-ba56-ed57540ae279</OID><TagName>HKN</TagName><Address>254</Address…' +43ms
  cbus:client rx response { commandId: 100, code: 344, matched: false, processed: false, type: 'response', raw: '[100] 344 End XML snippet' } +15ms
  cbus:client matched response '[100] 344 End XML snippet' to request '[100] dbgetxml //HOMEKITM/254' (0 pending requests) +3ms
  cbus:client rx unparsable line: '[100] 344 End XML snippet', exception: TypeError: Cannot read property 'address' of undefined
  cbus:client     at _arrayize.forEach.srcGroup (/usr/lib/node_modules/homebridge-cbus/lib/cgate-database.js:315:124)
  cbus:client     at Array.forEach (native)
  cbus:client     at _arrayize.forEach.srcApp (/usr/lib/node_modules/homebridge-cbus/lib/cgate-database.js:314:27)
  cbus:client     at Array.forEach (native)
  cbus:client     at _parseXML (/usr/lib/node_modules/homebridge-cbus/lib/cgate-database.js:306:45)
  cbus:client     at xml2js.parseString (/usr/lib/node_modules/homebridge-cbus/lib/cgate-database.js:283:19)
  cbus:client     at Parser.<anonymous> (/usr/lib/node_modules/homebridge-cbus/node_modules/xml2js/lib/xml2js.js:489:18)
  cbus:client     at emitOne (events.js:96:13)
  cbus:client     at Parser.emit (events.js:188:7)
  cbus:client     at Object.onclosetag (/usr/lib/node_modules/homebridge-cbus/node_modules/xml2js/lib/xml2js.js:447:26) +977ms
  cbus:client rx event { time: '20170315-211542', code: 753, processed: false, message: '//HOMEKITM/254 92feb400-eb9e-1034-ba56-ed57540ae279 Net Sync: address=7 type=DIMDN4 version=1.3.0 serial=100170.1322 catalog=L5504D2A', type: 'event', raw: '#e# 20170315-211542 753 //HOMEKITM/254 92feb400-eb9e-1034-ba56-ed57540ae279 Net Sync: address=7 type=DIMDN4 version=1.3.0 serial=100170.1322 catalog=L5504D2A' } +3s

The dbget command sent back 75 pages so I will email separately

Thanks for the help

Glen

**Comment by glenferguson** [comment]
Simon.

Dbgetxml file


Glen

**Comment by simonhac** [comment]
@glenferguson the file did not come through. please used the github interface (rather than email) where possible.

**Comment by glenferguson** [comment]
File attached Simon
[dbgetxml output.docx](https://github.com/anthonywebb/homebridge-cbus/files/846772/dbgetxml.output.docx)

**Comment by simonhac** [comment]
thanks @glenferguson -- i've downloaded the file and can reproduce it in my environment. i'll see if i can find a solution before the weekend.

(just a thought: for ~~~cybersecurity~~~ privacy reasons you may want to remove the file you attached above.)

**Comment by glenferguson** [comment]
Thanks a lot Simon

**Comment by simonhac** [comment]
@glenferguson when the C-Gate database is first generated for a project, each application contains a placeholder group, `<Unused>`. eg.:
```xml
<Application>
  <OID>930320d0-eb9e-1034-bb06-ed57540ae279</OID>
  <TagName>Heating</TagName>
  <Address>136</Address>
  <Group>
    <OID>930347e0-eb9e-1034-bb07-ed57540ae279</OID>
    <TagName>&lt;Unused&gt;</TagName>
    <Address>255</Address>
  </Group>
</Application>
```

somewhere along the way, the placeholder group for your `Air Conditioning` application was deleted:

```xml
<Application>
  <OID>9303bd10-eb9e-1034-bb0a-ed57540ae279</OID>
  <TagName>Air Conditioning</TagName>
  <Address>172</Address>
  <Description></Description>
</Application>

```
this shouldn't be a problem, but my parsing code assumed there'd always be at least one group, which it shouldn't have.

i have fixed this in [commit aaf30f163bd508cc8dcdcfac89237b02d1b7b036](https://github.com/anthonywebb/homebridge-cbus/pull/34/commits/aaf30f163bd508cc8dcdcfac89237b02d1b7b036) and it'll make its way into v0.5.9 once PR #34 is merged in and released to npm

in the meantime, you can probably get up and going by adding a placeholder to the `Air Conditioning` application.

**Comment by simonhac** [comment]
i believe this is now fixed. @glenferguson, please reopen if you see this again.

**Comment by glenferguson** [comment]
Thanks Simon, you are a legend. All worked great.

**Comment by simonhac** [comment]
my pleasure @glenferguson.
