### ISSUE TITLE
Ramping dim levels

### ISSUE THREAD

**Issue by barranak** [anthonywebb/homebridge-cbus#36]
Hi it would be great if we could ramp lights up and down on time schedules.

Morning alarm ramping lights upto a level over a time frame in minutes/seconds I use eve app in ios which allows time schedules for groups. As per you comment on the cbus forum adding a second accessory but with a rampduration attribute for use in scene controls

**Comment by simonhac** [comment]
ok @barranak -- so `homebridge-cbus` would take care of the ramp duration, and the `eve` app would be used for scheduling?

**Comment by barranak** [comment]
I could use ether homekit app or eve for scheduling.  Apple TV would maintain scheduled times for the home automation and could use an accessory with ramp duration in seconds or minutes to be used in the schedules scene control 
"type": "dimmer", "id": 3, "name": "Bedside Lamp" "rampDuration": "60 secs"
The eve app gives a brightness control with sliders for scene programming so would be looking for around 40% brightness to auto come on at 6am in the morning slowly increasing over a minutes duration.
Would the above be 60s from 0 > 100 % or from 0 > to the scene programed 40%

**Comment by simonhac** [comment]
fixed in v0.5.9.
