### ISSUE TITLE
Allowing for accessories with the same name?

### ISSUE THREAD

**Issue by anthonywebb** [anthonywebb/homebridge-cbus#38]
@simonhac originally when I had 2 accessories with the same name, for instance a "Fan", an error would be thrown.   I fixed that limitation in this commit:
https://github.com/anthonywebb/homebridge-cbus/commit/44f19f71e57a851717262bc782dcf2e4cd4a0f48

It looks like we lost that fix in this commit:
https://github.com/anthonywebb/homebridge-cbus/commit/098ee246f1fd9d10c81d0c415db5411dda612f97

I guess that we should decide whether we should force each accessory to have a unique name, or not.  Does anyone have an opinion on this issue?

**Comment by simonhac** [comment]
i personally don't mind if someone has two accessories with the same name -- though i think it'd be pretty confusing for siri and the `Home` app.

a UI configuration tool might want to warn against it, but how about we give users a bit of rope for now?

(a fairly common use case when you have a collection of objects is to clean up by renaming lots and lots of entities one by one. if you need to swap the names of some entities, it becomes tedious to have constraints on names when you're in the middle of adjusting.)

**Comment by anthonywebb** [comment]
I agree, I think we leave things as they are for the time being.

**Comment by EdwinJS** [comment]
A workaround for this is, naming two devices for example - like this:
# RoomX Fan
# RoomY Fan

And then in the home app name the rooms RoomX, and RoomY. When the fans are put in those rooms the name is overlapped and joined with the name. Hard to explain but once you do it itll make sense. Im sure many of us have done this but for those that havent, enjoy xx
