### ISSUE TITLE
Allow for arbitrary code/command execution?

### ISSUE THREAD

**Issue by anthonywebb** [anthonywebb/homebridge-cbus#39]
This is a little bit off in the weeds, and a lot more technical than most people would use, but hear me out.

My wife is not very technically minded.  She prefers physical interfaces to using apps and software to do things.  She told me that I could have a sonos audio system if she could turn it off and on witha  switch on the wall.

I solved her problem by creating a new virtual "lighting device" on my network, and tying the button on the light switch to that virtual device.

What I had was code that would listen for on/off events of that virtual device, and turn on and off the sonos.  Bingo, she had a switch on the wall that could turn on and off the music.

I am wondering if this project needs to have a similar construct.  One that can listen for traffic on predefined (in the config) devices, and do stuff (make http calls, email, sms, etc)  What it is is essentially a callback to your own code/commands anytime a devices level changes.

I see this being exposed in the config as an array of "rules" along with a set of "commands" that are to execute if the "expression" is true.  For example:

Turn the music on when a button on the wall is pressed
```
{
    "id":"1",
    "name":"Music On",
    "expression":"id=='95' && level==100",
    "commands":[
        {"type":"url","url":"http://music.restapi/on"},
     ]
}
```

Turn off the music and the lights off (after 30 seconds) when button on the wall is pressed
```
{
    "id":"1",
    "name":"Music On",
    "expression":"id=='95' && level==0",
    "commands":[
        {"type":"url","url":"http://music.restapi/off"},
        {"type":"delay","delay":30},
        {"type":"lighting","group":"53","level":0,"delay":0,"timeout":0}
     ]
}
```

Would this be of interest to anyone else?

**Comment by simonhac** [comment]
@anthonywebb i like the idea of a rules engine _a lot_, but i'm not sure that it belongs in `homebridge-cbus`. i think it'd be preferable to have a rules engine that sits on top of `homebridge` and can manage any number of accessories across any implemented platforms.

if a rules engine was built into `homebridge-cbus` it would only be available to C-Bus users, and would most likeley get a lot less developer love. also, the `commands` entity would gradually converge to become the equivalent of accessories for other platforms -- many of which are more complex than you'd want for a data-driven description.

how about casting around for opinions in the `homebridge` slack channel or [issues list](https://github.com/nfarina/homebridge/issues)?

(if you do decide to write a rules engine, be careful about the trap of using `eval`. probably good to study [json-rules-engine](https://github.com/cachecontrol/json-rules-engine) for inspiration.)

**Comment by anthonywebb** [comment]
@simonhac are you thinking this would be another plugin?  I'm not sure that a plugin would have access to all the level changes globally would it?  I think you are right though, a generic rules engine that any developers could leverage would be awesome!

**Comment by simonhac** [comment]
hey @anthonywebb -- thinking more about this, i think it would be best as a module outside of `homebridge-cbus`. if you agree, please close this issue.

**Comment by anthonywebb** [comment]
I would love it, would let the existing buttons/switches on my wall do other cool stuff.  Hoping I can find time to move this forward.

**Comment by simonhac** [comment]
i'd love it too. i suspect a good solution might involve [homebridge-websocket](https://github.com/cflurin/homebridge-websocket).

in fact, it might be possible to do it all with `Node-RED` and `homebridge-websocket`…
