### ISSUE TITLE
Cbus config.json.

### ISSUE THREAD

**Issue by rafiqaust** [anthonywebb/homebridge-cbus#43]
Hi I have installed cbus plugin in homebridge and how can I config.json. File and what next can u plz explain step by step I am not that expert thanks.

**Comment by anthonywebb** [comment]
I suppose the first thing to know is if you have a CNI and are running CGate somewhere on your network?  Do you know the IP address of the machine running CGate?  Is the homebridge you have running on the same machine as the CGate instance?  

If you can give a little more information about what you have tried and what your network topology looks like it would help us get you taken care of quicker.

**Comment by rafiqaust** [comment]
Hi I got static ip which is running my wiser2 and PCI interface device for programming. Thanks

**Comment by anthonywebb** [comment]
Sorry, I am not as familiar with the Wiser platform.  But for sure you will need to get an instance of CGate running in order to use homebridge and this plugin.

**Comment by rafiqaust** [comment]
Hi I do have Cgate running in my system. R u local I am in Sydney would u be able to discuss over the phone I am happy to pay u.thanks

**Comment by greiginsydney** [comment]
Hey @rafiqaust , ping me on Twitter: @greiginsydney. I'm a n00b with homebridge but might be able to help...

**Comment by rafiqaust** [comment]
Hi Greig can I email to u

**Comment by greiginsydney** [comment]
Hi @rafiqaust. I don't want to post my private e-mail in a public forum, so suggesting Twitter was a way of getting in personal contact with each other. How about you post a comment on something at greiginsydney.com? They're moderated, so I can pull your e-mail out and delete the comment. ;-)

**Comment by greiginsydney** [comment]
Hey @rafiqaust how did you go with the process I sent you? Any luck?

**Comment by rafiqaust** [comment]
Thanks I am working on it just waiting for raspberry to deliver. I will keep in touch how far I go.

**Comment by simonhac** [comment]
@rafiqaust how did you go? if this is resolved, please close the issue. thanks, simon.

**Comment by simonhac** [comment]
@rafiqaust ping!

**Comment by simonhac** [comment]
assuming this is closed. @rafiqaust please reopen if necessary.
