### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-cbus

### ISSUE THREAD

**Issue by lcrowhurst** [anthonywebb/homebridge-cbus#46]
On a rasberry pi 3 I have cgate and homebridge and homebridge-cbus running.
Ive upgraded to your latest version of Homebridge-cbus

Now when I run Home bridge I get this error:

 ====================
[4/25/2017, 10:17:39 AM] ERROR LOADING PLUGIN homebridge-cbus:
[4/25/2017, 10:17:39 AM] SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-cbus/lib/cgate-client.js:14:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
[4/25/2017, 10:17:39 AM] ====================

any ideas what I have done wrong?

**Comment by simonhac** [comment]
last time i saw something like this was in #26. 

suggest you take a look through and _ensure_ that you really have the right version of nodejs in your path...

**Comment by lcrowhurst** [comment]
What version should it be? How do I upgrade it?

Kind Regards,

Laurence Crowhurst

PO Box 62 , Frenchs Forest NSW 1641
T: +61 2 9402 0165 | M: 0407007351  |  E:  laurence@crowhurst.com.au<mailto:laurence@crowhurst.com.au>  | W: crowhurst.com.au<http://www.crowhurst.com.au/>
[escription: like-us-on-facebook]<http://www.facebook.com/CrowhurstTech>[magesVUUPLLCD]<http://www.linkedin.com/nhome/?trk=>

P Please consider the environment before printing this email
Disclaimer:: The contents of this email and any attached files are only for use of the intended recipient, as they may contain confidential and privileged information. Any dissemination, distribution or copying of this email or contents is strictly prohibited. If you are not the intended recipient please notify us immediately by return email and then erase the email. Any confidentiality or privilege is not waived or lost if you have received this email in error.
This email has been scanned for the presence of computer viruses however we exclude all liability for any viruses that may be contained in this email.Crowhurst Technical Consulting collects personal information to provide value-added services to our clients.

**Comment by simonhac** [comment]
please follow the instructions [here](https://github.com/anthonywebb/homebridge-cbus/issues/26#issuecomment-283785863) to find out what versions `homebridge` is trying to run with.

i suggest that you go with the latest LTS version, which is currently v6.10.2

**Comment by lcrowhurst** [comment]
Hi I got it working today, yes had to use the latest version.

Thanks for your help.

Regards
Laurence Crowhurst
0407 007 351

On 30 Apr 2017, at 10:47 pm, simonhac <notifications@github.com<mailto:notifications@github.com>> wrote:


please follow the instructions here<https://github.com/anthonywebb/homebridge-cbus/issues/26#issuecomment-283785863> to find out what versions homebridge is trying to run with.

i suggest that you go with the latest LTS version, which is currently v6.10.2

**Comment by simonhac** [comment]
glad that it works -- good luck going forward.
