### ISSUE TITLE
Small bug fix for Project names with digits

### ISSUE THREAD

**Issue by gbrooker** [anthonywebb/homebridge-cbus#5]
Hi Anthony,
thanks so much for your bus homebridge plugin, it's so much fun to use siri to control the lights at home ! There is a small bug in function CBusStatusPacket in cgate-client.js 

If the network name has digits, which mine does, the group number is not correctly decoded for a lighting message. This results in home kit getting out of sync with cubs, as it homebridge-cbus thinks things are in a different state to what they really are. The fix is easy:

In lines 312-313 in cgate-client.js change
        var temp = array[2].match(/\d+/g);
        this.group = temp[2];
->
        var temp = array[2].split("/");
        this.group = temp[3];

i.e instead of using a regex to extract each of the numbers in the address parameter into the temp array, it splits the address at '/' separators. The forth element ([3]) is the group number, following the standard bus address syntax //PROJ/NET/APPLICATION/GROUP 
NB the initial // was already stripped by the previous regexp.

Without this change, the array containing the status of the items gets mixed up with group id and application id, resulting in the confusion in the status array.

**Comment by anthonywebb** [comment]
This was fixed in the most recent version, thanks for the pull request.
