### ISSUE TITLE
help with my-platform.json

### ISSUE THREAD

**Issue by DarylMc** [anthonywebb/homebridge-cbus#60]
Could someone please describe in a bit more detail how to set up my-platform.json
I did get it going once but now I can't seem to figure out how to do it.
In my case homebridge is now running as a service with systemd.

**Comment by DarylMc** [comment]
I created a file my-platform.json in pi directory but it hasn't got any info loaded

**Comment by peterconn** [comment]
Hey @ we just had a blackout. i waited 15 min for my PI to start up once power was restored. I had no comms via home app. I didnt even have a screen as i still have my screen plugged into the pi. So i pulled the power and did a hard reset. Once booted it started the pi. i waited about 10 min + still no comms to home app. it was displaying no response. i logged into pi via another laptop and tried to telnet via putty, again no connection. I had to command sudo systemctl start hombridge, and viola.! Not sure if the timer failed? any thoughts.

**Comment by EdwinJS** [comment]
Have you referenced it in the config.json for homebridge?

**Comment by DarylMc** [comment]
@EdwinJS 
Thanks for the reply.
Yes I did that.
"platform_export": "my-platform.json",
I'm not sure what I need to do on the pi for that to work.

**Comment by DarylMc** [comment]
do i need to specify the location of my-platform.json?

**Comment by DarylMc** [comment]
It is working for me now.
Great feature for new installs.
Because I set homebridge to run as a service with username homebridge I had to change permissions for my-platform.json and also specify the location.
eg
**"platform_export": "/home/pi/my-platform.json",**

create and save my-platform.json in pi directory
then
**sudo chown -R homebridge:homebridge /home/pi/my-platform.json**
**sudo chmod 777 -R /home/pi/my-platform.json**

**Comment by anthonywebb** [comment]
@DarylMc I'm ready to take the plunge and try out the raspberrypi3 as my interface to homebridge.  What I am not finding, but I know has been mentioned several times is the final list of steps I need to take to make it happen?  Thanks for all your hard work and help in getting people a solid way to get started with homebridge.  I'm excited to check out your handiwork! :)

**Comment by DarylMc** [comment]
https://onedrive.live.com/?authkey=%21ANlD74Wg0RsHv98&id=142E343EE7CCA768%2119603&cid=142E343EE7CCA768

**Comment by anthonywebb** [comment]
@DarylMc thanks I will give it a try and get you some feedback!

**Comment by DarylMc** [comment]
@anthonywebb 
Thanks to all the folks like yourself who did all the clever stuff.
I think the instructions are good and would really like to know how you get on.

**Comment by DarylMc** [comment]
@anthonywebb 
I edited spreadsheet just now.
Have run through again from scratch to check seems OK
Used an existing xml instead of toolkit to get project to pi tag folder.
Added some instructions to get project xml to sd from pc at the start
Removed a reboot after starting homebridge.timer because it wasn't needed, just added time and could possibly interrupt homebridge first startup.

**Comment by peterconn** [comment]
Daryl, I have backed up and made and image of my working SD. I will format and start over and try platform.json. I'll buzz ya if I have any issues following your spreadsheet.

**Comment by DarylMc** [comment]
@peterconn 
Simon is looking to make some changes so that homebridge.timer is not required.
I'm pretty happy with the instructions and ran through them again last night.
This time was the first time I used an existing project xml rather than bringing it over with Toolkit.

**Comment by peterconn** [comment]
@DarylMc im creating an image on my latest working SD. Ill try to use platform.json for import. ill let you know if i have any issues.

**Comment by DarylMc** [comment]
@peterconn 
I just did a build from scratch and recorded it on video.
I'm going to have to edit it a bit to cut out downloads and cig breaks but it is only 1hr 30 min.
Went really smoothly.

**Comment by DarylMc** [comment]
Much less time than it will take to edit and upload.

**Comment by peterconn** [comment]
@DarylMc ok cool. Ill give it a go.

**Comment by DarylMc** [comment]
im hoping success is the first thing i hear back :)

**Comment by EdwinJS** [comment]
Let me know if any edited help is needed, I do that stuff for a living. 👍 

I am making a tutorial/showcase video of homebridge and homebridge-cbus that will also be released very soon.

**Comment by peterconn** [comment]
Instructions worked a treat. I'm trying it again tonight on the second Pi.

**Comment by DarylMc** [comment]
@EdwinJS @peterconn @anthonywebb 
Hi EdwinJs
I made a video to use in conjunction with the spreadsheet I compiled for beginners like myself.
I think it helps make it all look kind of easy.
Some mistakes in there and it is quite long.
Don't be too harsh on me :)
https://www.youtube.com/watch?v=OMFv0r23cgE&t=808s

**Comment by peterconn** [comment]
Excellent. Thanks Daryl.

Regards

Peter Constantopedos
________________________________
