### ISSUE TITLE
Timer to delay Homebridge service start with CGate service and Homebridge on Pi3

### ISSUE THREAD

**Issue by DarylMc** [anthonywebb/homebridge-cbus#64]
Just for information.
Pi3 with Homebridge and CGate running as services at reboot.

I had some trouble with Homebridge entering a semi unresponsive state after pi reboot and believe it was due to CGate not fully synced when Homebridge service starts.

I have made a timer to delay the start of Homebridge service and it works great but I just wanted to attach this info from CGate manual with estimates for the sync times. 

This should give a rough idea of CGate sync times and the delay required for different sized networks.

**Sync Stages
A sync proceeds through several stages. 
These are indicated in the log as SyncSubState values.
As a guideline:**

**Gateway initialisation (1 second)
Unit presence; and (1 second)
Unit duplicate check (15 seconds per 25 units)
Unit Identification (15 seconds per 25 units)
Bridge sync (1 second)
Unit sync (30 seconds per 25 units)
Application sync (1 second per application)**

**Comment by peterconn** [comment]
@DarylMc i find that mine take a few minutes to come up when rebooting. I have around 45 groups.

**Comment by DarylMc** [comment]
@peterconn 
What time do you have in the timer?
If you didn't change it I set it at 240 seconds.

**Comment by peterconn** [comment]
its 240 as per your text file

**Comment by DarylMc** [comment]
@simonhac knows about and we might not need the timer eventually.
