### ISSUE TITLE
Multiple Instances of Homebridge getting mixed up

### ISSUE THREAD

**Issue by glenferguson** [anthonywebb/homebridge-cbus#68]
Hi all,

First of all can a I say a huge thank you to all who have contributed to Homebridge for Cbus, It is amazing and I have had lots of fun getting it working.

I am not sure if this is a Homekit issue or a Hombridge. I have two Homebridge setups at two different houses, both using a PI for cgate and Homebridge. They both work great and I have just set them up to be available remotely through an AppleTV and an Ipad. I have used different ITunes accounts and have made one a guest on the home Ipad. Therefore I have two instances on my device for the two places, one direct and the other remote (Guest). I setup the second house with an imaged PI of the first house and then just re-configured for the local setup and I used a different pin to avoid confusion. I have also turned off Home Switching.

I have noticed 2 issues that I was hoping someone might understand. The first is that if I am at home and have wifi on, the remote instance only recognises about 1/3 of the devices and the rest are "no response". If I turn off Wifi and use 4G they come back up fine instantly.

Second issue - Having gone from one house to the other, I am now finding that the guest version is getting labels and status mixed up with the local house, ie a room in the home is showing up in the labels for the guest account. Switching still works back as it should.

I can work around it but thought someone might have an idea.

Thanks Glen

**Comment by DarylMc** [comment]
Wow quite a setup.

I use iPad for remote access and an iPhone at my small CBus network.
Slow response on wifi but fast response on 4G "is" something I have seen before.
I am pretty sure it is an Apple issue and I was able to find other instances with a Google search.

Having said that I am not having the problem anymore.
After a "lot" of playing around I did break something on icloud and had to reset it.
https://github.com/anthonywebb/homebridge-cbus/issues/61
It caused the phone and iPad to get out of sync.
I wouldn't say that is your problem but it might be something to consider.

**Comment by glenferguson** [comment]
Thanks DarylMc, I will have a look.

**Comment by DarylMc** [comment]
I did have the slow updating on wifi again today.
Turned off and on icloud account on both ipad and iphone and it did not seem to fix it.
At my home there is 2 wifi access points with the same SSID on 2.4ghz.
I have a suspicion that moving between them or moving from 4G to wifi with the phone while using the ipad as a home hub is causing the problem.
At no stage do I see the ipad having trouble to update Homebridge.

**Comment by glenferguson** [comment]
I moved between the two houses (obviously different Wifi access) and it corrupted the remote access version. I haven't been back to check it out but reseting icloud did not do anything. The interesting thing I have discovered is that the remote version on my ipad has a mix of local house and remote house elements. When I turn on the wifi connection, only the local element (mixed in where they shouldn't be) show up as connected and other come up as not connected. When I turn the wifi off and go 4 G it syncs back to the remote house properly but the icons are incorrectly labelled with local house elements.

**Comment by anthonywebb** [comment]
Here's hoping that updates to core OS in iOS 11 will bring us some new
goodies (and potentially some fixes) for stuff like this.

**Comment by DarylMc** [comment]
Maybe a good test would be to disable Home Hub.
I'm going to give that a go

**Comment by glenferguson** [comment]
@DarylMc my setups both work fine when it is just on Wifi, the issues kick in when I have to go through the Internet and the Home Hub. It is slower and I get the corruption. Btw, on my two setups I have about 70 devices each so I think I certainly am giving it a workout. Two teenage kids and they love it.

**Comment by DarylMc** [comment]
@glenferguson 
As far as I know Homebridge has a limit of 100 accessories.
I wonder between your two homes if that is the problem?

**Comment by glenferguson** [comment]
Hi all, think I have uncovered my problem. I changed the User name by one and the problem went away.

**Comment by DarylMc** [comment]
@glenferguson 
Could you give a bit more info?
Do you mean config.json username?

**Comment by glenferguson** [comment]
Yes, I changed the 30 to a 31 and the problem went away
