### ISSUE TITLE
Lock mechanism accessory 

### ISSUE THREAD

**Issue by peterconn** [anthonywebb/homebridge-cbus#69]
Hey guys,

How do you go about adding lock mechanism as an accessory "type" in config.json? Im currently using a shutter relay in which i have only used the open contact terminal. i have set the failsafe relay on shutter relay to 5 sec so when i tell siri to unlock, 5 sec later it relocks the strike, so in regards to unlocking and locking its fine. The issue i have is when i tell her to unlock it again i have to command to lock the door so the state of the shutter switch on homekit changes to closed prior to asking to unlock., or i manually push the shutter button so it changes state to closed then ask her to unlock.

hope this makes sense,

Thanks in advance

Pete

**Comment by PhilPearson** [comment]
A bell press might be better suited to this.
{ "type": "switch", "id": "9", "name": "Unlock", "activeDuration": "5 sec" }

**Comment by peterconn** [comment]
@PhilPearson, thanks Phil I’ll give that a shot.

**Comment by peterconn** [comment]
@PhilPearson, I tried with what you said, it works as an on off switch to lock and unlock the door though I have to ask Siri to turn on the front door as appose to open or unlock. I had it working with a shutter option where I can ask to open door and that worked though it would remain open and would not turn back to close.

**Comment by PhilPearson** [comment]
@peterconn, the only thing I can think of is to hack the shutter accessory code for your own use.
The code would look pretty similar to the trigger accessory I recently posted.
Its not something I would be adding to this repository due as the use case is pretty limited.
