### ISSUE TITLE
Thank you Anthony Webb 

### ISSUE THREAD

**Issue by RickHOZ** [anthonywebb/homebridge-cbus#71]
Hi Anthony,

Just wanted to say thank you for all your work. I found your information on Friday and it is now Sunday at 9 am and I have most of my house now being able to be controlled by voice. ( I did go to bed in between so not as bad as it sounds )

Amazing.

I am far from being experienced in any sort of programming but I managed through your notes and of course google to be able to install the required software on my mac OSX server and get it all up and running.

I really think you have a product here that should be explored, I think this could be put in a box and deployed.

Anyway if you want to discuss I would love to have a chat.

p.s. to see my home this has now been integrated into visit.  www.1samara.com

Thanks

Rick

**Comment by anthonywebb** [comment]
@RickHOZ thanks for the kind words, although I can not take all the credit, there are a lot of great people contributing to the project and I think together we are building something really awesome.  Very happy that it is bringing automation to people everywhere!
