### ISSUE TITLE
Problems with status on a new build pi3  Homebridge CBus and CGate

### ISSUE THREAD

**Issue by DarylMc** [anthonywebb/homebridge-cbus#79]
I just want to mention to anyone with a working Homebridge I am having status problems with a fresh install.
Also when restoring an older image.
I don't know why but will look at it this weekend.
Toolkit 1.15.2
iOS 11.2.1

**Comment by DarylMc** [comment]
Everything is working fine now.
I found a little problem with status on one accessory which would be a rare use case scenario.
It just happened to be the accessory I was turning on and off to confirm two way status updating was working nice.

Exhaust fan connected to a CBus dimmer output.
Accessory selected as "switch" in  Homebridge CBus config.
I believe "fan" accessory has the same effect.
Symptom, repeat turn off from Home app and repeat turn on from CBus motion sensor without closing and opening Home app resulted in occasional incorrect status.

Set accessory to "dimmer" and no problem noted.

**Comment by anthonywebb** [comment]
Thanks @DarylMc I will be building another pi as I lost the card in my PI during our last power outage.  You think the image I used last time is still a good starting point for the rebuild?  All my wife wants for christmas is to be able to see if the kids have flipped on the lights after she put them to bed :)

**Comment by DarylMc** [comment]
@anthonywebb 
Hi Anthony
Did you change much from the original image I sent?
It's still there.
https://1drv.ms/f/s!AminzOc-NC4UgZp-56BhJtbezCUpng
I can't recall any major alterations since then.
It would be nice if you could salvage your current Homebridge config file and xml.

**Comment by anthonywebb** [comment]
I dont think I changed at all from the original.  Unfortunately I am unable to boot that card at all, have tried it in multiple PI's, it is dead.  I'll set it up again, and will bake an image when it is complete.

**Comment by DarylMc** [comment]
Maybe you can not delete the home from phone.
Or is it too late?

**Comment by DarylMc** [comment]
Maybe it's not the done way but I'm  pretty excited about it.
I up samba to share pi folder and these.
User root to access.
   [CGate]
   comment=CGate
   path=/usr/local/bin/cgate
   browseable=Yes
   writeable=Yes
   valid users= pi, root
   only guest=no
   create mask=0777
   directory mask=0777
   public=no
   force user = root
 
   [configjson]
   comment=configjson
   path=/var/lib/homebridge
   browseable=Yes
   writeable=Yes
   valid users= pi, root
   only guest=no
   create mask=0777
   directory mask=0777
   public=no
   force user = root

   [boot]
   comment=boot
   path=/boot
   browseable=Yes
   writeable=Yes
   valid users= pi, root
   only guest=no
   create mask=0777
   directory mask=0777
   public=no
   force user = root
   
    [pi]
   comment=pi
   path=/home/pi
   browseable=Yes
   writeable=Yes
   valid users= pi, root
   only guest=no
   create mask=0777
   directory mask=0777
   public=no
   force user = root
   
# Comment
# run sudo smbpasswd -a pi and sudo smbpasswd -a root

**Comment by DarylMc** [comment]
@anthonywebb 
How did you go Anthony?
I have had SD cards fail on raspberry pi before.
Just one a few years ago.
Could you mention the size of your SD card.
I've got a super dooper 32GB Samsung Pro+ I mostly use which cost more than the raspberry pi.
It's had more than a few power failures with no apparent problems.
Also I have used a lot of Sandisk Ultra 16GB.
It writes a bit slower than the Samsung on the PC but it does seem quite reliable too.

Obviously a UPS is going to be more ideal but I wonder in practical terms if the card plays a role.
Specifically the size.
