### ISSUE TITLE
IOS 11.2.2 

### ISSUE THREAD

**Issue by peterconn** [anthonywebb/homebridge-cbus#82]
Has anyone updated to IOS 11.2.2? Upon updating i Did sudo rm accessory etc.. Re added new home and in homekit while deleting the old one. Homebridge starts and show active running though no Inputs in HomeKit are operational. I’m just wondering if there maybe a new version of homebridge? I also tried to telnet to Pi IP 192.168.1.xx port 20023 and cannot access that.

**Comment by srpage** [comment]
I’m running 11.2.2 on my phone. No issues found yet.

**Comment by DarylMc** [comment]
@peterconn 
Hi Peter
I haven't had any issues for the last couple of iOS updates.
If you cannot access CGate that will be the place to start.
Maybe check CGate logs and see what you can find?
/usr/local/bin/cgate/logs
Can you still SSH to the pi?

**Comment by peterconn** [comment]
@srpage @darylmc I think I have a bigger problem, I can’t ping my CNI. It’s plugged into switch but no light on the switch so the network is not seeing the device. When I log into my router it’s not even in the network map. Definitely the problem.

**Comment by DarylMc** [comment]
@peterconn 
If it is not just the power supply I'd guess it may be the ethernet interface.
Maybe the CBus interface board can still be put to some use.
Definitely consider sending it my way if you are going to put it in the bin.
Use the CBus and unit LED indicators to help find the problem.
If you need a new CNI I'd consider an RS232 PCI from ebay in conjunction with a serial device server.

Hopefully it is something simple.

**Comment by DarylMc** [comment]
At one stage I bought a CNI and had two PCI's on the network.
My RS232 interface is from 2002.
I bought a CNI not long after but it is just a distant memory of Lantronix nightmare setup now.
I really do believe newer CNI's setup must be better because you just don't see so many people on CBus forum struggling any more.
I think they have all been solid devices and my CNI most likely died from a lightning surge on the network coming through the ADSL copper.

I don't know when and I'm not feeling like I am missing features but somewhere along the way I think more features have been added to later PCI and CNI devices.
That's what diagnostic utility tells me anyway.

I'm still using the 2002  RS 232 interface.

**Comment by peterconn** [comment]
Since the lighting storm we had over a week ago, it stopped working. I’ve attended 2 sites in the area due to network routers being damaged due to lightning. I have an rs232 interface from a while ago when I completed my course, do I have to use a rs232 to Ethernet/rj45 converter?

**Comment by DarylMc** [comment]
I use a Moxa 5110A RS232 serial device server.
It's been good for nearly 10 years now.
If you get one I can tell you some settings.
The main one is to configure as TCP server.
The rest you will figure out easily.

**Comment by DarylMc** [comment]
Of course I never like to throw any CBus products in the bin.
Make sure it is not just the power supply.

**Comment by peterconn** [comment]
I think I’ll just buy a new CNI interface.

**Comment by DarylMc** [comment]
Or even worse a router or switch problem.
The CNI LED's can help

**Comment by peterconn** [comment]
@darylmc in regards to the CNI interface lights, the network lights status are  “Orange/Green flash
Link is good with active data transfer” yet when I unplug the network cable the light does not change status, it just keeps flashing. Orange/green. Power supply has been checked and still at 12v DC.

**Comment by peterconn** [comment]
@darylmc I’ve also tried different ports on The switch and no change. This is the only device on the network which is Inoperable.

**Comment by DarylMc** [comment]
@peterconn 
I can't help much right now.
In the installation instructions which you can probably download from CIS website it will have the LED info.
If it is a 5500CNI2 just search Google for installation instructions.

**Comment by peterconn** [comment]
@darylmc thanks, that’s where I got the info from ^^above^^

**Comment by DarylMc** [comment]
I'm sure you already tried but if you haven't remove CBus power from the device and power cycle it.

**Comment by peterconn** [comment]
@darylmc, yes first thing I tried. The fact that the status of the lights don’t change when the Ethernet cable is unplugged states there is an internal issue within the CNI.

**Comment by DarylMc** [comment]
Doesn't sound promising.
The ethernet device server and RS232 interface is a good cheaper option if it can fit in the space you have easily.
If you never used one you should grab one just to give it a go.
I've used them on solar inverters, CBus PCI. AC central control units and RS485 AC zone control.
You can get some models for RS232 only or selectable for RS232 or RS485

**Comment by DarylMc** [comment]
One thing in Homebridge CBus which I think is a bit of an issue.
If I unplug the ethernet cable for my serial device server or the RS232 cable to PCI Homebridge does not seem to notice or throw an error.
This would be especially bad for access control use because you would not have correct status and not know there was a problem.

I'm talking to another fellow this morning with CNI troubles.
His is Lantronix version and presumably about 10 years old.
For interest do you remember if your CNI is the Lantronix version or how old it is?
Can you access the CNI in your browser?

**Comment by andysyiros** [comment]
I had an issue with my CNI a couple of years ago.

The lights seemed to be flashing the correct colours but it still wouldn’t connect. Clipsal sent me a replacement CNI and that did the job. Months later, the new CNI stopped working.

 I soon realised it was the original power supply. The earlier CNIs operates at 12V and the newer CNIs operate between 6-12V. I can only image the power was dying a slow death?

I only worked this out after I replaced the power supply with the power supply that came with the replacement CNI. I have my power supply in the roof space so probably died in the heat. In the near future I will use a din rail power supply, but it is working now so haven’t been bothered.

**Comment by peterconn** [comment]
@DarylMc I just purchased a serial to Rj45 converter from Jcar for $140 and homekit is now operational. Configuration wasn't too hard. I can ssh to pi but Im still having an issue with telnet IP port 20023. Fault is "software caused connection abort".

**Comment by DarylMc** [comment]
It works?
So you kind of proved the CNI was faulty?
It's Sunday afternoon and I've had too many drinks to be giving advice now.
The Moxa ethernet device server is a really solid device.
There is a stack of cheaper Chinese versions around which do the same thing too. 
Moxa brand device should cost you about the same and be a really reliable thing.

**Comment by peterconn** [comment]
@darylmc yes everything is working I just can’t telnet to the device and check project list and net list.

**Comment by DarylMc** [comment]
> m

onnirmc@hotmail.com




















































































































































































































































hey you are not here 
you couldnotcomplsinif someone else was

**Comment by DarylMc** [comment]
dont come back tonight

**Comment by DarylMc** [comment]
Set the ip address to the same as your old CNI

Socket port of serial I/O
Change it to 10001 like the CNI was.
TCP server.

Check the serial settings
Start Bits : One
Data Bits : Eight
Stop Bit : One
Parity : None
Baud Rates : 9600

**Comment by peterconn** [comment]
@darylmc, I don’t need the settings for the new server as I got that working. HomeKit is now working and I can control all inputs. The only thing I can’t do is telnet to check project list and net list.

**Comment by DarylMc** [comment]
You can't telnet to the pi IP address port 20023?
Has your PC IP address changed.
If that's the problem you can set the last three numbers of access.txt file to 255 to allow your whole subnet.

**Comment by peterconn** [comment]
@darylmc, I think it has changed, I’ll check when I get home.

**Comment by DarylMc** [comment]
I think you will like using the ethernet device server.
It certainly is a cheaper option if you have an RS232 PCI at hand and breaks the possible failures into separate hardware devices.

**Comment by DarylMc** [comment]
I'm a bit rusted on with the Moxa brand.
From experience I know they are reliable.
And I am familiar with the configuration.

**Comment by peterconn** [comment]
@darylmc, the settings you listed were very similar with the one I got from Jaycar.

**Comment by DarylMc** [comment]
Yeah I downloaded and read the manual for your device.
I'm pretty sure the only thing you need to do now is update the access.txt file.

**Comment by DarylMc** [comment]
Everyone who did a CBus training course got a PCI.
If they now give out a USB PCI I'd ask if it is possible to get RS232 version.
It is a very useful device.

**Comment by peterconn** [comment]
@darylmc, funny enough I found 2 rs232 pci’s In my stash. One is dark blue and the other is light blue.

**Comment by DarylMc** [comment]
Hey light blue is before my time.

**Comment by DarylMc** [comment]
That's showing your age :)

**Comment by DarylMc** [comment]
Or experience

**Comment by DarylMc** [comment]
I tell you what 
I never learned so much about CBus until the last year and thanks to Homebridge CBus.
And it is not a lot but still a lot more than before.

**Comment by peterconn** [comment]
@darylmc only been 22 years and thanks to you I’ve learnt a lot more also
