### ISSUE TITLE
Support for blinds/shades/shutter/curtain/window-coverings

### ISSUE THREAD

**Issue by simonhac** [anthonywebb/homebridge-cbus#9]
i have a number of blinds and would love to control them via homekit.

my newer blinds are wired with [shutter relays](http://www.clipsal.com/Trade/Products/ProductDetail?CatNo=L5501RBCP) and i also have a number that use 2 relays from a [12 channel relay](http://www.clipsal.com/Trade/Products/ProductDetail?CatNo=L5512RVF).

if anyone is already working on this, please let me know. otherwise i'll bone up on HomeKit and node and have a crack at it.

any recommendations for documentation on HomeKit so i can see how it handles blinds? (i trust that the repo for HomeBridge is my best source for documentation on the HomeBridge architecture.)

**Comment by simonhac** [comment]
i've started looking at adding the 'Window Covering' service for shutter relays. completely outside homebridege-cbus, i'm using the HomeKit Accessory Simulator just to learn about the service.

it looks pretty simple -- at the simplest all i need to do is manage three characteristics:
* Current Position
* Target Position
* Position Start (although it seems that the Home app ignores this attribute)

![image](https://cloud.githubusercontent.com/assets/20500649/22086430/c9442494-de2c-11e6-9e21-748d07efe56a.png)

however, oddly i find that the app shows 'Opening…' or 'Closing…' long after the device has reached its target position:

![image](https://cloud.githubusercontent.com/assets/20500649/22086563/606c7eca-de2d-11e6-8ecc-b4f679b37f4c.png)

sometimes (ie. i can reproduce it, just not every time) the indicator just spins and spins and spins until the next time the Home app performs a read request on the service:

```
01/19/17 09:56:27: Learnomatic ][ (INFO) Read request performed on: service: Boris Window Covering, characteristic: Target Position
01/19/17 09:56:27: Learnomatic ][ (INFO) Read request performed on: service: Boris Window Covering, characteristic: Current Position
```

i've found that i can trigger this update by changing to a different app and then back again to Home app. weird. i don't normally like to blame other's work for weird bugs, but i can reproduce this easily. glad to have found it in the simulator before getting caught with it with my code.

now i have enough to go on with the characteristics, my next task is to work out how to send the right cbus commands to interact with the blinds. it's pretty arcane:

![image](https://cloud.githubusercontent.com/assets/20500649/22086821/c5ec9950-de2e-11e6-995d-b7296fda84d4.png)

**Comment by simonhac** [comment]
i've found lots of good examples of how to control other blinds with homebridge -- looks like it'll be pretty straightforward to implement the Window Covering accessory.

i have confirmed that i can control my blinds with c-bus commands:
```
ramp //SHAC/254/56/142 100% # open
ramp //SHAC/254/56/142 2% # close
ramp //SHAC/254/56/142 0% # stop
```

...however it looks like my installer accidentally got my shutter relays around the wrong way, so i'll need to add a boolean config parameter called something like `invert`.

**Comment by simonhac** [comment]
ok, i've had a good go at it.

looking pretty stable -- i'll run it for a day or two before sending @anthonywebb a pull request.

**Comment by simonhac** [comment]
@anthonywebb i have made a PR for a resolution of this issue -- homebridge-cbus can now support c-bus shutter relays. i hope you like it.

**Comment by anthonywebb** [comment]
Merged, thanks!

**Comment by msuMax** [comment]
@simonhac in the first post you've mentioned that you use some channels on a 12-channel relay for blind control. 
Do you control them as switch type or as shutter?
